@url_base = http://localhost:5003/api/comentario
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtIiwiZXhwIjoxNzUwMTIzNjQ3fQ.Tp1HTEOdVl2PFLOQuabecOdMfdSi_q2TgL4nArZXpVM

### Cadastrar comentário
POST {{url_base}}/cadastrar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "texto": "Ótimo produto!",
    "itemId": 1
}

### Listar comentários
GET {{url_base}}/listar
Authorization: Bearer {{token}}

### Deletar comentário
DELETE {{url_base}}/deletar/5
Authorization: Bearer {{token}}
